//
//  Constants.swift
//  WikiPediaFillUpGame
//
//  Created by Rukmani  on 02/08/17.
//  Copyright © 2017 rukmani. All rights reserved.
//

import Foundation

let blank = "__________"
let noOfSentencesRequired = 10

let paragraph = "When the user opens the app, it displays the text from a random Wikipedia page. (You’re free to use any logic for grabbing text from a random Wiki page) The game requires a minimum of 10 lines of text on the screen. However, we want to show complete paragraphs of text to make it easier to understand the content displayed. Use the least number of paragraphs required to cross the 10 sentence limit. Once you have the content for the game, proceed to remove words from the text to create 10 blanks. (Each sentence can have at most one blank) Once the blanks are ready, we’re ready to begin the game! Display the complete text to the user, with clearly visible blanks (preferably not just white space) at the appropriate places. When the user taps / clicks on a blank, a list of all the 10 words are shown (shuffled, of course!) and the user can choose one of them. The UI updates to show that the user has filled up that blank. The user can tap / click a submit button once he’s done and the app shows him his score out of 10. If the user does not fill any particular blank, then he does not get points for it. Along with the user score, a button to “Replay” the game is displayed. Upon tapping / clicking it, the game begins again with another random Wikipedia page. The game is simple. A user is displayed content from a random Wikipedia page. 10 words are removed from the content to create blanks. The user needs to fill in these blanks using a jumbled list of words that were removed. He/she gets a score out of 10, depending on the number of blanks that were correctly filled."


let flower = "A flower, sometimes known as a bloom or blossom, is the reproductive structure found in plants that are floral (plants of the division Magnoliophyta, also called angiosperms). The biological function of a flower is to effect reproduction, usually by providing a mechanism for the union of sperm with eggs. Flowers may facilitate outcrossing (fusion of sperm and eggs from different individuals in a population) or allow selfing (fusion of sperm and egg from the same flower). Some flowers produce diaspores without fertilization (parthenocarpy). Flowers contain sporangia and are the site where gametophytes develop. Many flowers have evolved to be attractive to animals, so as to cause them to be vectors for the transfer of pollen. After fertilization, the ovary of the flower develops into fruit containing seeds. In addition to facilitating the reproduction of flowering plants, flowers have long been admired and used by humans to bring beauty to their environment, and also as objects of romance, ritual, religion, medicine and as a source of food. The essential parts of a flower can be considered in two parts: the vegetative part, consisting of petals and associated structures in the perianth, and the reproductive or sexual parts. A stereotypical flower consists of four kinds of structures attached to the tip of a short stalk. Each of these kinds of parts is arranged in a whorl on the receptacle. The transition to flowering is one of the major phase changes that a plant makes during its life cycle. The transition must take place at a time that is favorable for fertilization and the formation of seeds, hence ensuring maximal reproductive success. To meet these needs a plant is able to interpret important endogenous and environmental cues such as changes in levels of plant hormones and seasonable temperature and photoperiod changes."
